name = "cmvl01-qxyx-route-edgetunnel"
main = "_worker.js"
compatibility_date = "2026-07-22"
account_id = "c7cbc7b3c716ca9929d73cd227290fd0"
workers_dev = false
keep_vars = true

routes = [
  { pattern = "cmvl01.qxyx.net/*", zone_name = "qxyx.net" }
]

[[kv_namespaces]]
binding = "KV"
id = "5e1be043e8c5487abefcb561115fabec"
